project:
  type: website

# add to website section for announcements
# announcement: 
#   icon: info-circle
#   dismissable: true
#   content: "**Learn R with me!** Register for my 2-day live virtual workshop, [_Introduction to R for Data Analysis_](https://instats.org/seminar/introduction-to-r-for-data-analysis-2014), on Jan 15-16."    
#   type: info
#   position: below-navbar

website:
  title: "Rebecca Barter"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Blog archive"
        file: blog.qmd
      - text: "Workshops and consulting"
        file: consulting.qmd 
      - text: "Books"
        menu:
          - text: "Veridical Data Science"
            href: https://www.vdsbook.com
          - text: "The R Workshop"
            href: https://www.r-workshop.org
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rlbarter
      - icon: twitter
        href: https://twitter.com/rlbarter
      - icon: rss
        href: index.xml
  google-analytics: "UA-90929425-1"
  site-url: https://www.rebeccabarter.com
  description: "Rebecca Barter's blog"
  twitter-card: true
format:
  html:
    theme: simplex
    linkcolor: "#6633c4"
    code-copy: true
    footnotes-hover: true
    css: styles.css




