project:
  type: website

website:
  title: "Rebecca Barter"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Learn Python with me!** Join my full-day virtual workshop, _Python for R Users_, on November 13th hosted by Instats. [Register now!](https://instats.org/seminar/python-for-r-users2)"
    type: info
    position: below-navbar
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Blog archive"
        file: blog.qmd
      - text: "Workshops and consulting"
        file: consulting.qmd 
      - text: "Veridical Data Science"
        href: https://www.vdsbook.com
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rlbarter
      - icon: twitter
        href: https://twitter.com/rlbarter
      - icon: rss
        href: index.xml
  google-analytics: "UA-90929425-1"
  site-url: https://www.rebeccabarter.com
  description: "Rebecca Barter's blog"
  twitter-card: true
format:
  html:
    theme: simplex
    linkcolor: "#6633c4"
    code-copy: true
    footnotes-hover: true
    css: styles.css




