<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rebecca Barter">
<meta name="dcterms.date" content="2017-08-18">
<meta name="description" content="Developing a clean and easy analysis workflow takes a really, really long time. In this post, I outline the workflow that I have developed over the last few years.">

<title>A Basic Data Science Workflow – Rebecca Barter</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script type="text/javascript">

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-90929425-1', 'auto');

ga('send', {
  hitType: 'pageview',
  'anonymizeIp': true,
});
</script>


<link rel="stylesheet" href="../styles.css">
<meta name="twitter:title" content="A Basic Data Science Workflow – Rebecca Barter">
<meta name="twitter:description" content="Developing a clean and easy analysis workflow takes a really, really long time. In this post, I outline the workflow that I have developed over the last few years.">
<meta name="twitter:card" content="summary">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Rebecca Barter</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../blog.html"> 
<span class="menu-text">Blog archive</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../consulting.html"> 
<span class="menu-text">Workshops and consulting</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-books" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Books</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-books">    
        <li>
    <a class="dropdown-item" href="https://www.vdsbook.com">
 <span class="dropdown-text">Veridical Data Science</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.r-workshop.org">
 <span class="dropdown-text">The R Workshop</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About Rebecca</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/rlbarter"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/rlbarter"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../index.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">A Basic Data Science Workflow</h1>
                  <div>
        <div class="description">
          Developing a clean and easy analysis workflow takes a really, really long time. In this post, I outline the workflow that I have developed over the last few years.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">R</div>
                <div class="quarto-category">workflow</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Rebecca Barter </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 18, 2017</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#obtaining-the-data-from-the-website" id="toc-obtaining-the-data-from-the-website" class="nav-link active" data-scroll-target="#obtaining-the-data-from-the-website">Obtaining the data from the website</a></li>
  <li><a href="#setting-up-the-project-directory" id="toc-setting-up-the-project-directory" class="nav-link" data-scroll-target="#setting-up-the-project-directory">Setting up the project directory</a></li>
  <li><a href="#loading-the-data-load.r" id="toc-loading-the-data-load.r" class="nav-link" data-scroll-target="#loading-the-data-load.r">Loading the data: <code>load.R</code></a>
  <ul class="collapse">
  <li><a href="#the-loaddata-function" id="toc-the-loaddata-function" class="nav-link" data-scroll-target="#the-loaddata-function">The <code>loadData()</code> function</a></li>
  </ul></li>
  <li><a href="#cleaning-the-data-clean.r" id="toc-cleaning-the-data-clean.r" class="nav-link" data-scroll-target="#cleaning-the-data-clean.r">Cleaning the data: <code>clean.R</code></a>
  <ul class="collapse">
  <li><a href="#the-cleandata-function" id="toc-the-cleandata-function" class="nav-link" data-scroll-target="#the-cleandata-function">The <code>cleanData()</code> function</a>
  <ul class="collapse">
  <li><a href="#making-columns-human-readable-renamecolumns" id="toc-making-columns-human-readable-renamecolumns" class="nav-link" data-scroll-target="#making-columns-human-readable-renamecolumns">Making columns human-readable: <code>renameColumns()</code></a></li>
  <li><a href="#recoding-missing-values-as-na-convertmissing" id="toc-recoding-missing-values-as-na-convertmissing" class="nav-link" data-scroll-target="#recoding-missing-values-as-na-convertmissing">Recoding missing values as <code>NA</code>: <code>convertMissing()</code></a></li>
  <li><a href="#ensuring-each-variable-has-the-correct-class-convertclass" id="toc-ensuring-each-variable-has-the-correct-class-convertclass" class="nav-link" data-scroll-target="#ensuring-each-variable-has-the-correct-class-convertclass">Ensuring each variable has the correct class: <code>convertClass()</code></a></li>
  </ul></li>
  </ul></li>
  <li><a href="#analysis-eda.rmd" id="toc-analysis-eda.rmd" class="nav-link" data-scroll-target="#analysis-eda.rmd">Analysis: <code>eda.Rmd</code></a></li>
  <li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables">List of variables downloaded from ATUX-X</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>Developing a seamless, clean workflow for data analysis is harder than it sounds, especially because this is something that is almost never explicitly taught. Apparently we are all just supposed to “figure it out for ourselves”. For most of us, when we start our first few analysis projects, we basically have no idea how we are going to structure all of our files, or even what files we will need to make. As we try more and more things in our analysis (perhaps generating a large number of unnecessary files called <code>analysis2.R</code>, <code>next-analysis.R</code>, <code>analysis-writeup.Rmd</code>, <code>data_clean.csv</code>, <code>regression_results.csv</code> and <code>data_all.csv</code> along the way), we find that our project folder gets jumbled and confusing. The frustration when we come back to the project 6 months later and can’t remember which file contained the code that lead to the final conclusions is all too real.</p>
<p>This is why I have decided to describe in (possibly too much) detail the data cleaning workflow that I have somehow ended up with. I find this workflow to be particularly useful when dealing with messy (and possibly large) datasets that need several cleaning steps. Note that I did not develop this workflow in conjunction with any resources, I simply figured out what worked best for me via trial-and-error (a process which took 5 years and is definitely still ongoing). There will be several other resources out there on the internet describing “optimal workflows”, and these are definitely worth a read too (although a quick google found surprisingly few with the level of detail needed for a beginner). The key is figuring out a workflow that works best for <em>you</em>. That may be similar to mine, or it may not be.</p>
<p>If you decide to keep reading (perhaps because you too suffer from messy-project-syndrome and want some relief), by the end of this post you will know far too much about me and how I spend my time. As you will discover, I am particularly thorough when I clean data, and can spend hours simply making sure that I know what is in the data and moulding it so that it exactly adheres precisely to the format that I consider “clean”.</p>
<p>In this post I will describe my thought process as I download, clean and prepare for analysis the data from the 2016 <strong>American Time Use Survey (ATUS)</strong>. I have written my process in sufficient detail such that you can follow along if you’d like to.</p>
<p>The <a href="https://www.bls.gov/tus/">American Time Use Survey</a> is a yearly survey administered by the U.S. Census Bureau and sponsored by the Bureau of Labor Statistics. As with all surveys, it is probably good practice to first get an idea of what kind of population its respondents are supposed to represent. According to their website, the survey is sent to a randomly selected individual from each household in a set of eligible households chosen so as to represent a range of demographic characteristics. The set of eligible households consist of those who have completed their final month of the <a href="https://www.bls.gov/cps/home.htm">Current Population Survey</a> (a monthly survey of households conducted by the Bureau of Census for the Bureau of Labor Statistics).</p>
<p>This survey data has been featured heavily on Nathan Yau’s blog, <a href="https://flowingdata.com/tag/time-use/">Flowing Data</a>, which is where I became aware of it (thanks Nathan!).</p>
<section id="obtaining-the-data-from-the-website" class="level1">
<h1>Obtaining the data from the website</h1>
<p>The ATUS data can be downloaded from the <a href="https://www.atusdata.org/atus/">American Time Use Survey Extract Builder</a> which is maintained by the Minnesota Population Center at the University of Minnesota.</p>
<p>To actually obtain the data, you need to click on “Build an Extract” in the left-hand “Data” menu item (or click on “Get Data” inside the “Create an Extract” box). While I was initially confused about what to do once I got to the page with the drop-down menus asking me to “Select Variables”, I decided to just go crazy and start clicking. I soon discovered that an “extract” refers to the subset of the data corresponding to whichever variables I like. Once inside each of these drop-down menu entries I needed to click on the yellow plus symbols under “cart” to add the variables to my extract.</p>
<p>After selecting the variables I wanted, I clicked on “Select Samples” and selected only the year 2016. I then went to my cart and clicked on “Create Data Extract” and I was taken to a page where I had to choose my data format. I <strong>changed the data format to .csv</strong> and submitted my extract by clicking on “Submit Extract”. Note that you need to create an account to download your selected data, but this only takes a second. Once your data has been created (they will email you when it is ready; this should only take about a minute), you can refresh the page and download the CSV data file!</p>
<p>It is also a good idea to download the basic codebook by right clicking on the link and selecting “Save Link As” (which will tell us what each of the variables mean). I saved the file as a .txt file rather than whatever .cbk (the default) is.</p>
<p>In case you’re interested, the variables I selected are listed at the <a href="#variables">end of this post</a>.</p>
</section>
<section id="setting-up-the-project-directory" class="level1">
<h1>Setting up the project directory</h1>
<p>Now that I have successfully downloaded the data (a file called <code>atus_00002.csv.gz</code>), I am ready to set up my project directory. This involved a few quick steps.</p>
<ol type="1">
<li><p>I made a directory called <code>ATUS/</code>. This is where my project is going to live.</p></li>
<li><p>Within <code>ATUS/</code>, I made two empty sub-directories <code>R/</code> and <code>data/</code></p></li>
<li><p>In the <code>R/</code> sub-directory I make two empty .R files called <code>load.R</code> and <code>clean.R</code>.</p></li>
<li><p>I then move the downloaded data and codebook files into <code>data/</code></p></li>
</ol>
<p>If you’re following along, my working directory now looks like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">/</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  atus_00002.csv.gz</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  atus_00002.txt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>R<span class="sc">/</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  clean.R</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  load.R</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>It should be pretty obvious what <code>load.R</code> and <code>clean.R</code> are going to be for: they will be for loading the data and then cleaning the data (shocking, I know!).</p>
<p>While I will later start conducting my analysis in an <code>eda.Rmd</code> file, I usually don’t want to do the initial data cleaning in this file as it can be long and annoying to have to scroll past. Instead, I prefer to have separate scripts containing functions for loading and cleaning the data which I will later call in my <code>eda.Rmd</code> file.</p>
</section>
<section id="loading-the-data-load.r" class="level1">
<h1>Loading the data: <code>load.R</code></h1>
<p>Time to start work in the <code>load.R</code> file! The first thing I want to do is attempt to load in the data. Sometimes this is painless and easy, and sometimes this is a nightmare (prompting a session of frantic googling on how to load obscure data types into R).</p>
<p>The first lines of code I write in <code>load.R</code> is as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># open zipped file for reading</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>unz <span class="ot">&lt;-</span> <span class="fu">gzfile</span>(<span class="st">"data/atus_00002.csv.gz"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># load in the data</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>time_use_orig <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(unz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>when I run it in the console, I am pleasantly surprised to find that it works without any issue.</p>
<p>I then take my first look at the data in the console using the <code>dim()</code> command to identify the dimension of the data and the <code>head()</code> command to view the first 6 rows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(time_use_orig)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10493    64</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(time_use_orig)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       CASEID YEAR NUMCONTACTS_CPS8  HRHHID_CPS8 HRHHID2_CPS8 STATEFIP HH_SIZE
1 2.01601e+13 2016                1 3.509403e+14         3011       13       3
2 2.01601e+13 2016                1 2.025055e+14         3011       51       2
3 2.01601e+13 2016                2 1.243705e+14         3111       11       4
4 2.01601e+13 2016                1 2.041305e+14         3011       26       4
5 2.01601e+13 2016                1 2.203965e+13         3011       29       2
6 2.01601e+13 2016                0 1.021017e+13         3011       12       5
  FAMINCOME HH_NUMKIDS HH_NUMADULTS PERNUM LINENO     WT06 AGE SEX RACE HISPAN
1         3          0            3      1      1 24588650  62   2  100    100
2         6          0            2      1      1  5445941  69   1  110    100
3         4          2            2      1      1  8782622  24   2  110    100
4         8          3            1      1      1  3035910  31   2  100    100
5        13          0            2      1      1  6978586  59   2  100    100
6         5          4            1      1      1  5191610  16   2  120    244
  ASIAN MARST AGE_CPS8 SEX_CPS8 EDUC EDUCYRS SCHLCOLL SCHLCOLL_CPS8 EMPSTAT
1   999     1       62        2   21     112       99            98       5
2   999     1       69        1   16     111       99            98       5
3   999     6       24        2   20     102        1             1       5
4   999     4       31        2   30     214        1             4       1
5   999     1       59        2   21     112       99            98       1
6   999     6       16        2   15     110        3             1       5
  OCC2   OCC IND2   IND FULLPART UHRSWORKT UHRSWORK1 UHRSWORK2 EARNWEEK
1 9999 99999 9999 99999       99      9999       999       999 99999.99
2 9999 99999 9999 99999       99      9999       999       999 99999.99
3 9999 99999 9999 99999       99      9999       999       999 99999.99
4  130  3600  251  8180        2        32        32       999   469.44
5  125  2540  240  7860        2        12         6         6   302.50
6 9999 99999 9999 99999       99      9999       999       999 99999.99
  PAIDHOUR EARNRPT HOURWAGE HRSATRATE OTUSUAL    OTPAY UHRSWORKT_CPS8
1       99      99   999.99       999      99 99999.99           9999
2       99      99   999.99       999      99 99999.99           9999
3       99      99   999.99       999      99 99999.99           9999
4        1       1    14.67        32       0 99999.99             40
5        1       3    17.00       999       0 99999.99             55
6       99      99   999.99       999      99 99999.99           9999
  UHRSWORK1_CPS8 UHRSWORK2_CPS8 HRSWORKT_CPS8 ACT_CAREHH ACT_CARENHH ACT_EDUC
1            999            999          9999          0           0        0
2            999            999          9999          0           0        0
3            999            999          9999          0           0        0
4             40            999            40         60           0        0
5             30             25            55          0           0        0
6            999            999          9999          0           0        0
  ACT_FOOD ACT_GOVSERV ACT_HHACT ACT_HHSERV ACT_PCARE ACT_PHONE ACT_PROFSERV
1       40           0       190          0       715         0            0
2       30           0       230          0       620         0            0
3       75           0       105          0      1060         0            0
4      165           0       395          0       655        45            0
5       30           0       250          0       580       120            0
6      120           0       100          0       620         0            0
  ACT_PURCH ACT_RELIG ACT_SOCIAL ACT_SPORTS ACT_TRAVEL ACT_VOL ACT_WORK
1         0         0        465          0         30       0        0
2         0         0        560          0          0       0        0
3        60         0         20          0         60       0        0
4         0         0        120          0          0       0        0
5        18        60        177          0         75     130        0
6         0         0        355         50         35       0        0
  ERS_ASSOC ERS_PRIM
1         0       40
2         0       30
3         0       75
4         0      165
5        15       30
6         0      120</code></pre>
</div>
</div>
<p>It is pretty clear that everything is coded numerically and the variable names are fairly meaningless to a human. Fortunately, the codebook explains all. I spend some time browsing it.</p>
<section id="the-loaddata-function" class="level2">
<h2 class="anchored" data-anchor-id="the-loaddata-function">The <code>loadData()</code> function</h2>
<p>To make things simple in the long-run, I turn the above commands into a reusable function called <code>loadData()</code>. This function will have only one argument that specifies the path of the data in the local directory (relative to the <code>load.R</code> file). I usually set the default path to be the actual path for my setup.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># a function to load in the data</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>loadData <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">path_to_data =</span> <span class="st">"data/atus_00002.csv.gz"</span>) {</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># open zipped file for reading</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  unz <span class="ot">&lt;-</span> <span class="fu">gzfile</span>(path_to_data)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># load in the data</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read.csv</span>(unz)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To test my function, I simply run in my console by typing</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>time_use_orig <span class="ot">&lt;-</span> <span class="fu">loadData</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and look at the output of <code>head(time_use_orig)</code>.</p>
<p>Obviously such a function is a bit redundant in this setting: it is just as easy to write <code>read.csv(gzfile("data/atus_00002.csv.gz"))</code> in my eventual <code>eda.Rmd</code> file as it is to write <code>loadData("data/atus_00002.csv.gz")</code>. The reason I keep the <code>load.R</code> file in this case is because this is just my default workflow. I always load in my data using a function called <code>loadData</code>. In some situations, there are many, many things that need to be done in order to load the data, meaning that my <code>loadData</code> function can be fairly complicated. For example, sometimes column names need to be read in separately and then attached to the data, and sometimes I need to play with the format of the data to get R to play nice.</p>
</section>
</section>
<section id="cleaning-the-data-clean.r" class="level1">
<h1>Cleaning the data: <code>clean.R</code></h1>
<p>Next, I need to make some decisions about whether to keep the data in its raw, ugly form, or to spend some time making my life easier in the long-run by converting the column names to human-readable versions and converting the numeric codes for each variable to text descriptive characters or factors.</p>
<p>I also need to ensure that missing values are coded as <code>NA</code>s and that the class of each variable is what I would expect. For example, when I looked at the <code>head()</code> of the data above, I noticed that the <code>CASEID</code> variable is printed as a numeric in scientific notation, which is not ideal. IDs should probably be factors or characters (I go back and forth a lot on which I prefer)!</p>
<p>In <code>clean.R</code> I start work on a function called <code>cleanData()</code>. Like <code>loadData()</code>, the function <code>cleanData()</code> is always a part of my workflow.</p>
<p>When I eventually start the <code>eda.Rmd</code> file, I will load and clean the data like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define the loadData() function</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"load.R"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># define the cleanData() function</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"clean.R"</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># load the raw data</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>time_use_orig <span class="ot">&lt;-</span> <span class="fu">loadData</span>(<span class="st">"data/atus_00002.csv.gz"</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># clean the data</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>time_use <span class="ot">&lt;-</span> <span class="fu">cleanData</span>(time_use_orig)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="the-cleandata-function" class="level2">
<h2 class="anchored" data-anchor-id="the-cleandata-function">The <code>cleanData()</code> function</h2>
<p>The <code>cleanData()</code> function will actually call three separate functions, each performing a single task. These functions are</p>
<ul>
<li><p><code>renameColumns()</code>: an optional part of my workflow that changes the column names of each of my columns so that I can actually understand what they mean.</p></li>
<li><p><code>convertMissing()</code>: a function which converts missing values to <code>NA</code></p></li>
<li><p><code>convertClass</code>: a function which sets factor variables to factors, sets character variables to characters, etc</p></li>
</ul>
<section id="making-columns-human-readable-renamecolumns" class="level3">
<h3 class="anchored" data-anchor-id="making-columns-human-readable-renamecolumns">Making columns human-readable: <code>renameColumns()</code></h3>
<p>I hate reading column names that are all-caps, use ridiculous abbreviations and generally don’t adhere to my definition of “aesthetically pleasing”. Thus, whenever possible, I tend to convert my column names to human-readable versions. This is fairly tedious whenever the data has more than around 10 variables or so, but the process itself of renaming the variables is a very effective way of ensuring that you have a good idea of which variables are even in the data.</p>
<p>A word of caution: it is extremely important to check that you have correctly renamed the variables, since it is very easy to assign the wrong name to a variable, resulting in misleading conclusions.</p>
<p>Obviously this step is not practical if you have more than 100 or so variables (although I once did it with a dataset that had around 300 variables!). In addition, if I will at some point need to present the data to people who are very familiar with the original variable names, I won’t do any renaming either.</p>
<p>In this case, however, I have no particular allegiance to the original variable names and I want to make it as clear as possible (to myself, at least) what they mean.</p>
<p>To change the variable names, the <code>renameColumns()</code> function will leverage the <code>dplyr</code> function, <code>select()</code>. Note that I also drop a few variables at this stage that I decided weren’t interesting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>renameColumns <span class="ot">&lt;-</span> <span class="cf">function</span>(data) {</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="at">id =</span> CASEID,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">year =</span> YEAR,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>                          <span class="co"># number of attempted contacts</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">num_contacts =</span> NUMCONTACTS_CPS8,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>                          <span class="at">state =</span> STATEFIP,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>                          <span class="at">household_size =</span> HH_SIZE,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>                          <span class="at">family_income =</span> FAMINCOME,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>                          <span class="at">num_children =</span> HH_NUMKIDS,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>                          <span class="at">num_adults =</span> HH_NUMADULTS,</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>                          <span class="at">age =</span> AGE,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>                          <span class="at">sex =</span> SEX,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>                          <span class="at">race =</span> RACE,</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>                          <span class="at">marital_status =</span> MARST,</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>                          <span class="at">education_level =</span> EDUC,</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>                          <span class="at">education_years =</span> EDUCYRS,</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>                          <span class="at">employment_status =</span> EMPSTAT,</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>                          <span class="at">occupation_category =</span> OCC2,</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>                          <span class="at">occupation_industry =</span> IND2,</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>                          <span class="at">employed_full_time =</span> FULLPART,</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>                          <span class="at">hours_usually_worked =</span> UHRSWORKT,</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>                          <span class="at">weekly_earning =</span> EARNWEEK,</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>                          <span class="at">paid_hourly =</span> PAIDHOUR,</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>                          <span class="at">hourly_wage =</span> HOURWAGE,</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>                          <span class="at">hours_worked_hourly_rate =</span> HRSATRATE,</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_caring_household =</span> ACT_CAREHH,</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_caring_non_household =</span> ACT_CARENHH,</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_education =</span> ACT_EDUC,</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_eating =</span> ACT_FOOD,</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_gov =</span> ACT_GOVSERV,</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_household_activities =</span> ACT_HHACT,</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_household_services =</span> ACT_HHSERV,</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_personal_care =</span> ACT_PCARE,</span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_phone =</span> ACT_PHONE,</span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_personal_care_services =</span> ACT_PROFSERV,</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_shopping =</span> ACT_PURCH,</span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_religion =</span> ACT_RELIG,</span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_leisure =</span> ACT_SOCIAL,</span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_sports =</span> ACT_SPORTS,</span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_travelling =</span> ACT_TRAVEL,</span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_volunteer =</span> ACT_VOL,</span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_working =</span> ACT_WORK)</span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(data)</span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I then test the function out by writing</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>time_use <span class="ot">&lt;-</span> <span class="fu">renameColumns</span>(time_use_orig)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>in the console, and looking at the output of <code>head(time_use)</code>.</p>
<p>Now, I am fully aware that this function I have just written is not generalizable to alternate subsets of the data variables. This will be one of only two places where I will need to change things if I want to re-run the analysis on a different subset of variables (the second place will be when I explicitly convert numeric variables to their character counterparts). I’m facing a trade-off between generalizability of my pipeline and having human-readable data. If I were intending to repeat this analysis on different variables, I would either remove the part of the workflow where I rename the variables (as well as the part where I convert numeric variables to meaningful factors later on), or I would set the variable names as an argument in the <code>renameColumns()</code> function (but sadly, <code>select()</code> doesn’t play very nicely with variables read in as character strings, so I try to avoid this).</p>
</section>
<section id="recoding-missing-values-as-na-convertmissing" class="level3">
<h3 class="anchored" data-anchor-id="recoding-missing-values-as-na-convertmissing">Recoding missing values as <code>NA</code>: <code>convertMissing()</code></h3>
<p>If you took a look at the codebook, you will have noticed that there are many different ways to say that data is missing. This can be very problematic.</p>
<p>The most common way to code missingness in this data is to code it as <code>99</code> <code>999</code>, <code>9999</code>, etc (depending on whether the entries for the variable are two, three, four or more digit numbers, respectively). These entries are referred to in the codebook as <code>NIU (Not in universe)</code>. Other types of missing values are recorded such as <code>996</code> corresponding to <code>Refused</code>, <code>997</code> corresponding to <code>Don't know</code> and <code>998</code> corresponding to <code>Blank</code>.</p>
<p>I now need to decide what to convert to <code>NA</code>, keeping in mind that I need to be particularly careful for the variables with many different types of missingness (such as people who refused to answer, didn’t know or simply left the entry blank). I decide to take a look to see how widespread these types of missingness are by running the following code in the console:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># identify how many times informative missingness occurs for each variable</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>informative_missing <span class="ot">&lt;-</span> <span class="fu">sapply</span>(time_use, </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                              <span class="cf">function</span>(x) <span class="fu">sum</span>(x <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">996</span>, <span class="dv">997</span>, <span class="dv">998</span>)))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># print out only the non-zero values</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>informative_missing[informative_missing <span class="sc">!=</span> <span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          weekly_earning hours_worked_hourly_rate time_spent_personal_care 
                       1                       12                        1 
      time_spent_leisure       time_spent_working 
                       1                        1 </code></pre>
</div>
</div>
<p>Since these types of missingness are extremely rare, I decide to simply lump them in with all of the other <code>NA</code> values.</p>
<p>Next, I want to identify which variables have missing values coded as a varying number of 9s. Since the missing values are always supposed to correspond to the maximum, I printed out the maximum of each variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print out the maximum of each column</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(time_use, max)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                               id                              year 
                     2.016121e+13                      2.016000e+03 
                     num_contacts                             state 
                     8.000000e+00                      5.600000e+01 
                   household_size                     family_income 
                     1.300000e+01                      1.600000e+01 
                     num_children                        num_adults 
                     9.000000e+00                      8.000000e+00 
                              age                               sex 
                     8.500000e+01                      2.000000e+00 
                             race                    marital_status 
                     4.000000e+02                      6.000000e+00 
                  education_level                   education_years 
                     4.300000e+01                      3.210000e+02 
                employment_status               occupation_category 
                     5.000000e+00                      9.999000e+03 
              occupation_industry                employed_full_time 
                     9.999000e+03                      9.900000e+01 
             hours_usually_worked                    weekly_earning 
                     9.999000e+03                      9.999999e+04 
                      paid_hourly                       hourly_wage 
                     9.900000e+01                      9.999900e+02 
         hours_worked_hourly_rate       time_spent_caring_household 
                     9.990000e+02                      8.800000e+02 
  time_spent_caring_non_household              time_spent_education 
                     9.100000e+02                      1.000000e+03 
                time_spent_eating                    time_spent_gov 
                     6.350000e+02                      4.700000e+02 
  time_spent_household_activities     time_spent_household_services 
                     1.184000e+03                      4.500000e+02 
         time_spent_personal_care                  time_spent_phone 
                     1.434000e+03                      4.200000e+02 
time_spent_personal_care_services               time_spent_shopping 
                     5.250000e+02                      6.000000e+02 
              time_spent_religion                time_spent_leisure 
                     7.130000e+02                      1.392000e+03 
                time_spent_sports             time_spent_travelling 
                     1.260000e+03                      1.265000e+03 
             time_spent_volunteer                time_spent_working 
                     9.200000e+02                      1.350000e+03 </code></pre>
</div>
</div>
<p>I notice here that there are several variables with missing values as their maxima such as <code>occupation_industry</code> with a maximum of <code>9999</code>, and <code>hourly_wage</code> with a maximum of <code>999.99</code>. Since I don’t really want to manually convert these missing values to <code>NA</code>, I decide to automate it using the <code>mutate_if()</code> function from the <code>dplyr</code> package. First I write a few helper functions in the <code>clean.R</code> file for calculating the maximum of a vector and for identifying specific values in a vector.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Helper function for identifying missing values equal to 99, 999, etc</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>equalFun <span class="ot">&lt;-</span> <span class="cf">function</span>(x, value) {</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  x <span class="sc">==</span> value</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Helper function for identifying if the max of a variable is equal to 99, ...</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>maxFun <span class="ot">&lt;-</span> <span class="cf">function</span>(x, value) {</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">max</span>(x, <span class="at">na.rm =</span> T) <span class="sc">==</span> value</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The first argument of <code>mutate_if()</code> is a function which returns a Boolean value specifying which columns to select. The second argument is wrapped in <code>funs()</code> and itself is a function which specifies what to do to each column. <code>if_else(equalFun(., 99), NA_integer_, .)</code> can be read aloud as “If the value is equal to 99, convert it to a <code>NA</code> of integer type, otherwise do nothing” (the <code>.</code> serves as a placeholder for the data, like <code>x</code> in <code>function(x)</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>convertMissing <span class="ot">&lt;-</span> <span class="cf">function</span>(data) {</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># convert missing values to NA</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 99 to NA</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="dv">99</span>), </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="dv">99</span>), <span class="cn">NA_integer_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 999 to NA</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="dv">999</span>), </span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="dv">999</span>), <span class="cn">NA_integer_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 9999 to NA</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="dv">9999</span>), </span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="dv">9999</span>), <span class="cn">NA_integer_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 999.99 to NA</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="fl">999.99</span>), </span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="fl">999.99</span>), <span class="cn">NA_real_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 99999.99 to NA</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="fl">99999.99</span>), </span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="fl">99999.99</span>), <span class="cn">NA_real_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 998 to NA</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="dv">998</span>), </span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="dv">998</span>), <span class="cn">NA_integer_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 997 to NA</span></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="dv">997</span>), </span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="dv">997</span>), <span class="cn">NA_integer_</span>, .)))</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(data)    </span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>It took some playing around with running the body of the function in the console (with <code>data</code> defined as <code>time_use</code>) to get it to run without errors (I was getting errors to do with <code>NA</code> values and realized that I needed to add <code>na.rm = T</code> in the <code>maxFun()</code> function).</p>
<p>Once the body runs in the console, I then check to make sure that the complete function worked as expected by running it in the console and checking out the summary of the output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># convert the missing values to NAs</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>time_use <span class="ot">&lt;-</span> <span class="fu">convertMissing</span>(time_use)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check out the summary</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(time_use)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       id                 year       num_contacts        state      
 Min.   :2.016e+13   Min.   :2016   Min.   :0.0000   Min.   : 1.00  
 1st Qu.:2.016e+13   1st Qu.:2016   1st Qu.:0.0000   1st Qu.:13.00  
 Median :2.016e+13   Median :2016   Median :0.0000   Median :27.00  
 Mean   :2.016e+13   Mean   :2016   Mean   :0.2574   Mean   :27.96  
 3rd Qu.:2.016e+13   3rd Qu.:2016   3rd Qu.:0.0000   3rd Qu.:42.00  
 Max.   :2.016e+13   Max.   :2016   Max.   :8.0000   Max.   :56.00  
                                                                    
 household_size   family_income    num_children      num_adults   
 Min.   : 1.000   Min.   : 1.00   Min.   :0.0000   Min.   :1.000  
 1st Qu.: 1.000   1st Qu.: 8.00   1st Qu.:0.0000   1st Qu.:1.000  
 Median : 2.000   Median :12.00   Median :0.0000   Median :2.000  
 Mean   : 2.657   Mean   :10.85   Mean   :0.7706   Mean   :1.868  
 3rd Qu.: 4.000   3rd Qu.:14.00   3rd Qu.:1.0000   3rd Qu.:2.000  
 Max.   :13.000   Max.   :16.00   Max.   :9.0000   Max.   :8.000  
                                                                  
      age             sex             race       marital_status 
 Min.   :15.00   Min.   :1.000   Min.   :100.0   Min.   :1.000  
 1st Qu.:35.00   1st Qu.:1.000   1st Qu.:100.0   1st Qu.:1.000  
 Median :49.00   Median :2.000   Median :100.0   Median :3.000  
 Mean   :49.42   Mean   :1.555   Mean   :104.5   Mean   :3.022  
 3rd Qu.:64.00   3rd Qu.:2.000   3rd Qu.:100.0   3rd Qu.:6.000  
 Max.   :85.00   Max.   :2.000   Max.   :400.0   Max.   :6.000  
                                                                
 education_level education_years employment_status occupation_category
 Min.   :10.00   Min.   :101.0   Min.   :1.000     Min.   :110.0      
 1st Qu.:21.00   1st Qu.:112.0   1st Qu.:1.000     1st Qu.:122.0      
 Median :30.00   Median :214.0   Median :1.000     Median :131.0      
 Mean   :29.74   Mean   :187.8   Mean   :2.559     Mean   :138.1      
 3rd Qu.:40.00   3rd Qu.:217.0   3rd Qu.:5.000     3rd Qu.:150.0      
 Max.   :43.00   Max.   :321.0   Max.   :5.000     Max.   :200.0      
                                                   NA's   :4119       
 occupation_industry employed_full_time hours_usually_worked weekly_earning  
 Min.   :100.0       Min.   :1.000      Min.   :   0.0       Min.   :   0.0  
 1st Qu.:160.0       1st Qu.:1.000      1st Qu.:  38.0       1st Qu.: 458.8  
 Median :220.0       Median :1.000      Median :  40.0       Median : 800.0  
 Mean   :210.4       Mean   :1.219      Mean   : 672.6       Mean   : 994.0  
 3rd Qu.:251.0       3rd Qu.:1.000      3rd Qu.:  50.0       3rd Qu.:1346.2  
 Max.   :300.0       Max.   :2.000      Max.   :9995.0       Max.   :2884.6  
 NA's   :4119        NA's   :4119       NA's   :4119         NA's   :4833    
  paid_hourly     hourly_wage    hours_worked_hourly_rate
 Min.   :1.000   Min.   : 0.00   Min.   : 1.00           
 1st Qu.:1.000   1st Qu.:10.50   1st Qu.:28.00           
 Median :1.000   Median :15.00   Median :40.00           
 Mean   :1.444   Mean   :18.34   Mean   :33.86           
 3rd Qu.:2.000   3rd Qu.:22.00   3rd Qu.:40.00           
 Max.   :2.000   Max.   :99.99   Max.   :90.00           
 NA's   :4833    NA's   :7348    NA's   :8438            
 time_spent_caring_household time_spent_caring_non_household
 Min.   :  0.00              Min.   :  0.000                
 1st Qu.:  0.00              1st Qu.:  0.000                
 Median :  0.00              Median :  0.000                
 Mean   : 31.85              Mean   :  8.603                
 3rd Qu.: 11.00              3rd Qu.:  0.000                
 Max.   :880.00              Max.   :910.000                
                                                            
 time_spent_education time_spent_eating time_spent_gov    
 Min.   :   0.00      Min.   :  0.00    Min.   :  0.0000  
 1st Qu.:   0.00      1st Qu.: 30.00    1st Qu.:  0.0000  
 Median :   0.00      Median : 60.00    Median :  0.0000  
 Mean   :  15.39      Mean   : 64.99    Mean   :  0.3647  
 3rd Qu.:   0.00      3rd Qu.: 90.00    3rd Qu.:  0.0000  
 Max.   :1000.00      Max.   :635.00    Max.   :470.0000  
                                                          
 time_spent_household_activities time_spent_household_services
 Min.   :   0.0                  Min.   :  0.0000             
 1st Qu.:  15.0                  1st Qu.:  0.0000             
 Median :  75.0                  Median :  0.0000             
 Mean   : 121.1                  Mean   :  0.9868             
 3rd Qu.: 180.0                  3rd Qu.:  0.0000             
 Max.   :1184.0                  Max.   :450.0000             
                                                              
 time_spent_personal_care time_spent_phone  time_spent_personal_care_services
 Min.   :   0.0           Min.   :  0.000   Min.   :  0.000                  
 1st Qu.: 495.0           1st Qu.:  0.000   1st Qu.:  0.000                  
 Median : 570.0           Median :  0.000   Median :  0.000                  
 Mean   : 580.3           Mean   :  6.774   Mean   :  4.747                  
 3rd Qu.: 660.0           3rd Qu.:  0.000   3rd Qu.:  0.000                  
 Max.   :1434.0           Max.   :420.000   Max.   :525.000                  
                                                                             
 time_spent_shopping time_spent_religion time_spent_leisure time_spent_sports
 Min.   :  0.00      Min.   :  0.0       Min.   :   0.0     Min.   :   0.00  
 1st Qu.:  0.00      1st Qu.:  0.0       1st Qu.: 130.0     1st Qu.:   0.00  
 Median :  0.00      Median :  0.0       Median : 260.0     Median :   0.00  
 Mean   : 24.15      Mean   : 13.4       Mean   : 298.4     Mean   :  20.22  
 3rd Qu.: 30.00      3rd Qu.:  0.0       3rd Qu.: 432.0     3rd Qu.:   0.00  
 Max.   :600.00      Max.   :713.0       Max.   :1392.0     Max.   :1260.00  
                                                                             
 time_spent_travelling time_spent_volunteer time_spent_working
 Min.   :   0.0        Min.   :  0.000      Min.   :   0.0    
 1st Qu.:  20.0        1st Qu.:  0.000      1st Qu.:   0.0    
 Median :  55.0        Median :  0.000      Median :   0.0    
 Mean   :  71.5        Mean   :  8.469      Mean   : 157.7    
 3rd Qu.:  95.0        3rd Qu.:  0.000      3rd Qu.: 375.0    
 Max.   :1265.0        Max.   :920.000      Max.   :1350.0    
                                                              </code></pre>
</div>
</div>
<p>Scrolling through the summary, I notice a few peculiarities. In particular, there are several variables that have stupidly large values. For example the maximum value for <code>hours_usually_worked</code> is <code>9995</code> (this didn’t appear in the codebook!). I decided to look at a histogram of this variable to see how typical this value is. I ran the following code in the console:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(time_use) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> hours_usually_worked))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 4119 rows containing non-finite values (`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="2017-08-16-data-science-workflow_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>From the histogram, it is fairly clear that there is an additional type of missing value (405 samples have a value of <code>9995</code>) that was not mentioned in the documentation. I then go back and update my <code>convertMissing()</code> function to include this extra missing value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>convertMissing <span class="ot">&lt;-</span> <span class="cf">function</span>(data) {</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># convert missing values to NA</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 99 to NA</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="dv">99</span>), </span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="dv">99</span>), <span class="cn">NA_integer_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 999 to NA</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="dv">999</span>), </span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="dv">999</span>), <span class="cn">NA_integer_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 9999 to NA</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="dv">9999</span>), </span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="dv">9999</span>), <span class="cn">NA_integer_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 999.99 to NA</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="fl">999.99</span>), </span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="fl">999.99</span>), <span class="cn">NA_real_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 99999.99 to NA</span></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="fl">99999.99</span>), </span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="fl">99999.99</span>), <span class="cn">NA_real_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 998 to NA</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="dv">998</span>), </span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="dv">998</span>), <span class="cn">NA_integer_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 997 to NA</span></span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="dv">997</span>), </span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="dv">997</span>), <span class="cn">NA_integer_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 9995 to NA</span></span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="dv">9995</span>), </span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="dv">9995</span>), <span class="cn">NA_integer_</span>, .))) </span>
<span id="cb31-28"><a href="#cb31-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(data)    </span>
<span id="cb31-29"><a href="#cb31-29" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, I ran the <code>convertMissing()</code> function again the data and re-made the histogram to make sure that everything was going smoothly.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># re-run the renameColumns() function</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>time_use <span class="ot">&lt;-</span> <span class="fu">renameColumns</span>(time_use_orig)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="co"># convert missing values to NA</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>time_use <span class="ot">&lt;-</span> <span class="fu">convertMissing</span>(time_use)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># re-make the histogram</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(time_use) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> hours_usually_worked))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 4524 rows containing non-finite values (`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="2017-08-16-data-science-workflow_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Now that that was sorted out, it occurred to me that I wasn’t sure what kind of scale the <code>time_spent</code> variables were on (is it hours spent in the last week? In the last month? The last year? Perhaps it is minutes spent over the last day? It probably should have occurred to me to ask this earlier, but it didn’t. Whatever… I’m asking it now! After spending some time perusing the internet for a while, I found <a href="https://www.bls.gov/news.release/atus.t01.htm">this table</a> which summarised the average hours spend <em>per day</em> on a range of activities. For example, it said that on average, people spend 9.58 hours per day on “personal care activities”. The histogram below shows the distribution of values for the <code>time_spent_personal_care</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(time_use) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> time_spent_personal_care))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="2017-08-16-data-science-workflow_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The mean value in the data is 580, which when divided by 60 gives 9.6. From this “evidence” I conclude that what the data contains is the <strong>number of minutes spent per day</strong>. Whether this is averaged over a week, or is based on one particular day, I honestly don’t know. But for my purposes, I’ll just take each value as the number of minutes spent on the activity on a “typical” day.</p>
</section>
<section id="ensuring-each-variable-has-the-correct-class-convertclass" class="level3">
<h3 class="anchored" data-anchor-id="ensuring-each-variable-has-the-correct-class-convertclass">Ensuring each variable has the correct class: <code>convertClass()</code></h3>
<p>The final cleaning task involves converting categorical values to have a categorical variable class (such as a factor), and other things along these lines involving variable classes.</p>
<p>Recall that the person ID variable, <code>CASEID</code>, is currently coded as a numeric (which is printed in scientific notation). In general, it is good practice to code IDs as factors (or characters).</p>
<p>There are also many other variables that should be coded as factors: state, sex, race, marital_status, education_level, family_income, employment_status, occupation_category, and occupation_industry.</p>
<p>Now begins the part of my cleaning process that often takes the longest: I am going to convert each of these numeric variables not only to factors, but to <em>meaningful</em> factors. I don’t want to make plots for genders 1 and 2, or for states 42 and 28; I want to make plots for males and females and for states Pennsylvania and Mississippi.</p>
<p>First, for each variable I need to define a data frame that stores the conversion from number to meaningful category. Fortunately, this information was found in the codebook, and I can copy and paste these code conversions into separate .txt files and save them in the <code>data/</code> folder: <code>states.txt</code>, <code>occupation_industry.txt</code>, <code>occupation_category.txt</code>, etc. I can then read them into R as tab-delimited text files.</p>
<p>In case you’re interested, after copying the subsets of the codebook, my project directory now looks like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">/</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  atus_00002.csv.gz</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  atus_00002.txt</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  education_level.txt</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  employment_status.txt</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  family_income.txt</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  marital_status.txt</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  occupation_category.txt</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>  occupation_industry.txt</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>  race.txt</span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>  sex.txt</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>  state.txt</span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>R<span class="sc">/</span></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>  clean.R</span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a>  load.R</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I now start work on a <code>convertClass()</code> function which will be the third component of my <code>cleanData()</code> function. The first thing I do in <code>convertClass()</code> is convert the <code>id</code> variable to a factor. I then loop through each of the other factor variables to read in the code conversions from the .txt files, join the meaningful factors onto the original data frame using <code>left_join()</code> and remove the numeric version of the variable. The function that I wrote is presented below. I spent a while playing around in the console with various versions of the function below (always running code from the .R file rather than typing directly in the console itself).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>convertClass <span class="ot">&lt;-</span> <span class="cf">function</span>(data, <span class="at">path_to_codes =</span> <span class="st">"data/"</span>) {</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># convert id to a factor</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">id =</span> <span class="fu">as.factor</span>(id))</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># loop through each of the factor variables and convert to meaningful</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># factor then add to data frame</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (variable <span class="cf">in</span> <span class="fu">c</span>(<span class="st">"state"</span>, <span class="st">"occupation_industry"</span>, <span class="st">"occupation_category"</span>,</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"education_level"</span>, <span class="st">"race"</span>, <span class="st">"marital_status"</span>, <span class="st">"sex"</span>,</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"employment_status"</span>, <span class="st">"family_income"</span>)) {</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># identify the path to the code file</span></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>    path <span class="ot">&lt;-</span> <span class="fu">paste0</span>(path_to_codes, variable, <span class="st">".txt"</span>)</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># read in the code file</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>    codes <span class="ot">&lt;-</span> <span class="fu">read.table</span>(path, <span class="at">sep =</span> <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>)</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># remove the second column (the entries are separated by two \t's)</span></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>    codes <span class="ot">&lt;-</span> codes[, <span class="sc">-</span><span class="dv">2</span>]</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># convert the column names</span></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">colnames</span>(codes) <span class="ot">&lt;-</span> <span class="fu">c</span>(variable, <span class="fu">paste0</span>(variable, <span class="st">"_name"</span>))</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># add the code to the original data frame</span></span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>    data <span class="ot">&lt;-</span> <span class="fu">left_join</span>(data, codes, <span class="at">by =</span> variable)</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># remove old variable and replace with new variable</span></span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>    data[, variable] <span class="ot">&lt;-</span> data[, <span class="fu">paste0</span>(variable, <span class="st">"_name"</span>)]</span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>    data <span class="ot">&lt;-</span> data[, <span class="sc">!</span>(<span class="fu">colnames</span>(data) <span class="sc">%in%</span> <span class="fu">paste0</span>(variable, <span class="st">"_name"</span>))]</span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(data)</span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After I was done, I tested out that the <code>convertClass()</code> did what I hoped by running the following code in the console:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># run the convertClass() function</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>time_use <span class="ot">&lt;-</span> <span class="fu">convertClass</span>(time_use)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="co"># compare the original variables with the meaningful versions</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(time_use)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              id year num_contacts                state household_size
1 20160101160045 2016            1              Georgia              3
2 20160101160066 2016            1             Virginia              2
3 20160101160069 2016            2 District of Columbia              4
4 20160101160083 2016            1             Michigan              4
5 20160101160084 2016            1             Missouri              2
6 20160101160094 2016            0              Florida              5
       family_income num_children num_adults age    sex
1   $7,500 to $9,999            0          3  62 Female
2 $15,000 to $19,999            0          2  69   Male
3 $10,000 to $12,499            2          2  24 Female
4 $25,000 to $29,999            3          1  31 Female
5 $60,000 to $74,999            0          2  59 Female
6 $12,500 to $14,999            4          1  16 Female
                             race           marital_status
1                      White only Married - spouse present
2                      Black only Married - spouse present
3                      Black only            Never married
4                      White only                 Divorced
5                      White only Married - spouse present
6 American Indian, Alaskan Native            Never married
                 education_level education_years employment_status
1 High school graduate (diploma)             112              &lt;NA&gt;
2                     11th grade             111              &lt;NA&gt;
3     High school graduate (GED)             102              &lt;NA&gt;
4     Some college but no degree             214         Full time
5 High school graduate (diploma)             112         Full time
6                     10th grade             110              &lt;NA&gt;
                           occupation_category
1                                         &lt;NA&gt;
2                                         &lt;NA&gt;
3                                         &lt;NA&gt;
4               Healthcare support occupations
5 Education, training, and library occupations
6                                         &lt;NA&gt;
                     occupation_industry employed_full_time
1                                   &lt;NA&gt;                 NA
2                                   &lt;NA&gt;                 NA
3                                   &lt;NA&gt;                 NA
4 Health care services, except hospitals                  2
5                   Educational services                  2
6                                   &lt;NA&gt;                 NA
  hours_usually_worked weekly_earning paid_hourly hourly_wage
1                   NA             NA          NA          NA
2                   NA             NA          NA          NA
3                   NA             NA          NA          NA
4                   32         469.44           1       14.67
5                   12         302.50           1       17.00
6                   NA             NA          NA          NA
  hours_worked_hourly_rate time_spent_caring_household
1                       NA                           0
2                       NA                           0
3                       NA                           0
4                       32                          60
5                       NA                           0
6                       NA                           0
  time_spent_caring_non_household time_spent_education time_spent_eating
1                               0                    0                40
2                               0                    0                30
3                               0                    0                75
4                               0                    0               165
5                               0                    0                30
6                               0                    0               120
  time_spent_gov time_spent_household_activities time_spent_household_services
1              0                             190                             0
2              0                             230                             0
3              0                             105                             0
4              0                             395                             0
5              0                             250                             0
6              0                             100                             0
  time_spent_personal_care time_spent_phone time_spent_personal_care_services
1                      715                0                                 0
2                      620                0                                 0
3                     1060                0                                 0
4                      655               45                                 0
5                      580              120                                 0
6                      620                0                                 0
  time_spent_shopping time_spent_religion time_spent_leisure time_spent_sports
1                   0                   0                465                 0
2                   0                   0                560                 0
3                  60                   0                 20                 0
4                   0                   0                120                 0
5                  18                  60                177                 0
6                   0                   0                355                50
  time_spent_travelling time_spent_volunteer time_spent_working
1                    30                    0                  0
2                     0                    0                  0
3                    60                    0                  0
4                     0                    0                  0
5                    75                  130                  0
6                    35                    0                  0</code></pre>
</div>
</div>
<p>Everything looks good! I add <code>renameColumns()</code>, <code>convertMissing()</code> and <code>convertClass()</code> to the <code>cleanData()</code> function. I’m finally done with the cleaning component of my workflow. I may have to come back and add additional steps as I make unpleasant discoveries in my analysis, but for now, I can move on.</p>
<p>Below I print my final <code>clean.R</code> file</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># filename: clean.R</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Main function for data cleaning stage</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>cleanData <span class="ot">&lt;-</span> <span class="cf">function</span>(data) {</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># rename each of the columns to be human-readable</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># ignore some of the useless columns (such as alternative ID columns)</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> <span class="fu">renameColumns</span>(data)</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># convert missing data to NA</span></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> <span class="fu">convertMissing</span>(data)</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># convert integers to meaningful factors</span></span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> <span class="fu">convertClass</span>(data)</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(data)</span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a><span class="co"># rename each of the columns to be human-readable</span></span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a>renameColumns <span class="ot">&lt;-</span> <span class="cf">function</span>(data) {</span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="at">id =</span> CASEID,</span>
<span id="cb50-18"><a href="#cb50-18" aria-hidden="true" tabindex="-1"></a>                          <span class="at">year =</span> YEAR,</span>
<span id="cb50-19"><a href="#cb50-19" aria-hidden="true" tabindex="-1"></a>                          <span class="co"># number of attempted contacts</span></span>
<span id="cb50-20"><a href="#cb50-20" aria-hidden="true" tabindex="-1"></a>                          <span class="at">num_contacts =</span> NUMCONTACTS_CPS8,</span>
<span id="cb50-21"><a href="#cb50-21" aria-hidden="true" tabindex="-1"></a>                          <span class="at">state =</span> STATEFIP,</span>
<span id="cb50-22"><a href="#cb50-22" aria-hidden="true" tabindex="-1"></a>                          <span class="at">household_size =</span> HH_SIZE,</span>
<span id="cb50-23"><a href="#cb50-23" aria-hidden="true" tabindex="-1"></a>                          <span class="at">family_income =</span> FAMINCOME,</span>
<span id="cb50-24"><a href="#cb50-24" aria-hidden="true" tabindex="-1"></a>                          <span class="at">num_children =</span> HH_NUMKIDS,</span>
<span id="cb50-25"><a href="#cb50-25" aria-hidden="true" tabindex="-1"></a>                          <span class="at">num_adults =</span> HH_NUMADULTS,</span>
<span id="cb50-26"><a href="#cb50-26" aria-hidden="true" tabindex="-1"></a>                          <span class="at">age =</span> AGE,</span>
<span id="cb50-27"><a href="#cb50-27" aria-hidden="true" tabindex="-1"></a>                          <span class="at">sex =</span> SEX,</span>
<span id="cb50-28"><a href="#cb50-28" aria-hidden="true" tabindex="-1"></a>                          <span class="at">race =</span> RACE,</span>
<span id="cb50-29"><a href="#cb50-29" aria-hidden="true" tabindex="-1"></a>                          <span class="at">marital_status =</span> MARST,</span>
<span id="cb50-30"><a href="#cb50-30" aria-hidden="true" tabindex="-1"></a>                          <span class="at">education_level =</span> EDUC,</span>
<span id="cb50-31"><a href="#cb50-31" aria-hidden="true" tabindex="-1"></a>                          <span class="at">employment_status =</span> EMPSTAT,</span>
<span id="cb50-32"><a href="#cb50-32" aria-hidden="true" tabindex="-1"></a>                          <span class="at">occupation_category =</span> OCC2,</span>
<span id="cb50-33"><a href="#cb50-33" aria-hidden="true" tabindex="-1"></a>                          <span class="at">occupation_industry =</span> IND2,</span>
<span id="cb50-34"><a href="#cb50-34" aria-hidden="true" tabindex="-1"></a>                          <span class="at">employed_full_time =</span> FULLPART,</span>
<span id="cb50-35"><a href="#cb50-35" aria-hidden="true" tabindex="-1"></a>                          <span class="at">hours_usually_worked =</span> UHRSWORKT,</span>
<span id="cb50-36"><a href="#cb50-36" aria-hidden="true" tabindex="-1"></a>                          <span class="at">weekly_earning =</span> EARNWEEK,</span>
<span id="cb50-37"><a href="#cb50-37" aria-hidden="true" tabindex="-1"></a>                          <span class="at">paid_hourly =</span> PAIDHOUR,</span>
<span id="cb50-38"><a href="#cb50-38" aria-hidden="true" tabindex="-1"></a>                          <span class="at">hourly_wage =</span> HOURWAGE,</span>
<span id="cb50-39"><a href="#cb50-39" aria-hidden="true" tabindex="-1"></a>                          <span class="at">hours_worked_hourly_rate =</span> HRSATRATE,</span>
<span id="cb50-40"><a href="#cb50-40" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_caring_household =</span> ACT_CAREHH,</span>
<span id="cb50-41"><a href="#cb50-41" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_caring_non_household =</span> ACT_CARENHH,</span>
<span id="cb50-42"><a href="#cb50-42" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_education =</span> ACT_EDUC,</span>
<span id="cb50-43"><a href="#cb50-43" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_eating =</span> ACT_FOOD,</span>
<span id="cb50-44"><a href="#cb50-44" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_gov =</span> ACT_GOVSERV,</span>
<span id="cb50-45"><a href="#cb50-45" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_household_activities =</span> ACT_HHACT,</span>
<span id="cb50-46"><a href="#cb50-46" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_household_services =</span> ACT_HHSERV,</span>
<span id="cb50-47"><a href="#cb50-47" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_personal_care =</span> ACT_PCARE,</span>
<span id="cb50-48"><a href="#cb50-48" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_phone =</span> ACT_PHONE,</span>
<span id="cb50-49"><a href="#cb50-49" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_personal_care_services =</span> ACT_PROFSERV,</span>
<span id="cb50-50"><a href="#cb50-50" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_shopping =</span> ACT_PURCH,</span>
<span id="cb50-51"><a href="#cb50-51" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_religion =</span> ACT_RELIG,</span>
<span id="cb50-52"><a href="#cb50-52" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_leisure =</span> ACT_SOCIAL,</span>
<span id="cb50-53"><a href="#cb50-53" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_sports =</span> ACT_SPORTS,</span>
<span id="cb50-54"><a href="#cb50-54" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_travelling =</span> ACT_TRAVEL,</span>
<span id="cb50-55"><a href="#cb50-55" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_volunteer =</span> ACT_VOL,</span>
<span id="cb50-56"><a href="#cb50-56" aria-hidden="true" tabindex="-1"></a>                          <span class="at">time_spent_working =</span> ACT_WORK)</span>
<span id="cb50-57"><a href="#cb50-57" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(data)    </span>
<span id="cb50-58"><a href="#cb50-58" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb50-59"><a href="#cb50-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-60"><a href="#cb50-60" aria-hidden="true" tabindex="-1"></a><span class="co"># identify missing values equal to 99, 999, etc</span></span>
<span id="cb50-61"><a href="#cb50-61" aria-hidden="true" tabindex="-1"></a>equalFun <span class="ot">&lt;-</span> <span class="cf">function</span>(x, value) {</span>
<span id="cb50-62"><a href="#cb50-62" aria-hidden="true" tabindex="-1"></a>  x <span class="sc">==</span> value</span>
<span id="cb50-63"><a href="#cb50-63" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb50-64"><a href="#cb50-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-65"><a href="#cb50-65" aria-hidden="true" tabindex="-1"></a><span class="co"># identify if the max of a variable is equal to 99, 999, etc</span></span>
<span id="cb50-66"><a href="#cb50-66" aria-hidden="true" tabindex="-1"></a>maxFun <span class="ot">&lt;-</span> <span class="cf">function</span>(x, value) {</span>
<span id="cb50-67"><a href="#cb50-67" aria-hidden="true" tabindex="-1"></a>  <span class="fu">max</span>(x, <span class="at">na.rm =</span> T) <span class="sc">==</span> value</span>
<span id="cb50-68"><a href="#cb50-68" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb50-69"><a href="#cb50-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-70"><a href="#cb50-70" aria-hidden="true" tabindex="-1"></a><span class="co"># convert weird missing values to NA</span></span>
<span id="cb50-71"><a href="#cb50-71" aria-hidden="true" tabindex="-1"></a>convertMissing <span class="ot">&lt;-</span> <span class="cf">function</span>(data) {</span>
<span id="cb50-72"><a href="#cb50-72" aria-hidden="true" tabindex="-1"></a>  <span class="co"># convert missing values to NA</span></span>
<span id="cb50-73"><a href="#cb50-73" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb50-74"><a href="#cb50-74" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 99 to NA</span></span>
<span id="cb50-75"><a href="#cb50-75" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="dv">99</span>), </span>
<span id="cb50-76"><a href="#cb50-76" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="dv">99</span>), <span class="cn">NA_integer_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb50-77"><a href="#cb50-77" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 999 to NA</span></span>
<span id="cb50-78"><a href="#cb50-78" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="dv">999</span>), </span>
<span id="cb50-79"><a href="#cb50-79" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="dv">999</span>), <span class="cn">NA_integer_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb50-80"><a href="#cb50-80" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 9999 to NA</span></span>
<span id="cb50-81"><a href="#cb50-81" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="dv">9999</span>), </span>
<span id="cb50-82"><a href="#cb50-82" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="dv">9999</span>), <span class="cn">NA_integer_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb50-83"><a href="#cb50-83" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 999.99 to NA</span></span>
<span id="cb50-84"><a href="#cb50-84" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="fl">999.99</span>), </span>
<span id="cb50-85"><a href="#cb50-85" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="fl">999.99</span>), <span class="cn">NA_real_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb50-86"><a href="#cb50-86" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 99999.99 to NA</span></span>
<span id="cb50-87"><a href="#cb50-87" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="fl">99999.99</span>), </span>
<span id="cb50-88"><a href="#cb50-88" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="fl">99999.99</span>), <span class="cn">NA_real_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb50-89"><a href="#cb50-89" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 998 to NA</span></span>
<span id="cb50-90"><a href="#cb50-90" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="dv">998</span>), </span>
<span id="cb50-91"><a href="#cb50-91" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="dv">998</span>), <span class="cn">NA_integer_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb50-92"><a href="#cb50-92" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 997 to NA</span></span>
<span id="cb50-93"><a href="#cb50-93" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="dv">997</span>), </span>
<span id="cb50-94"><a href="#cb50-94" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="dv">997</span>), <span class="cn">NA_integer_</span>, .))) <span class="sc">%&gt;%</span></span>
<span id="cb50-95"><a href="#cb50-95" aria-hidden="true" tabindex="-1"></a>    <span class="co"># mutate all missing values coded as 9995 to NA</span></span>
<span id="cb50-96"><a href="#cb50-96" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(<span class="cf">function</span>(x) <span class="fu">maxFun</span>(x, <span class="dv">9995</span>), </span>
<span id="cb50-97"><a href="#cb50-97" aria-hidden="true" tabindex="-1"></a>              <span class="fu">funs</span>(<span class="fu">if_else</span>(<span class="fu">equalFun</span>(., <span class="dv">9995</span>), <span class="cn">NA_integer_</span>, .))) </span>
<span id="cb50-98"><a href="#cb50-98" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(data)</span>
<span id="cb50-99"><a href="#cb50-99" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb50-100"><a href="#cb50-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-101"><a href="#cb50-101" aria-hidden="true" tabindex="-1"></a><span class="co"># change numerics to meaningful factors</span></span>
<span id="cb50-102"><a href="#cb50-102" aria-hidden="true" tabindex="-1"></a>convertClass <span class="ot">&lt;-</span> <span class="cf">function</span>(data, <span class="at">path_to_codes =</span> <span class="st">"data/"</span>) {</span>
<span id="cb50-103"><a href="#cb50-103" aria-hidden="true" tabindex="-1"></a>  <span class="co"># convert id to a factor</span></span>
<span id="cb50-104"><a href="#cb50-104" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">id =</span> <span class="fu">as.factor</span>(id))</span>
<span id="cb50-105"><a href="#cb50-105" aria-hidden="true" tabindex="-1"></a>  <span class="co"># loop through each of the factor variables</span></span>
<span id="cb50-106"><a href="#cb50-106" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (variable <span class="cf">in</span> <span class="fu">c</span>(<span class="st">"state"</span>, <span class="st">"occupation_industry"</span>, <span class="st">"occupation_category"</span>,</span>
<span id="cb50-107"><a href="#cb50-107" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"education_level"</span>, <span class="st">"race"</span>, <span class="st">"marital_status"</span>, <span class="st">"sex"</span>,</span>
<span id="cb50-108"><a href="#cb50-108" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"employment_status"</span>, <span class="st">"family_income"</span>)) {</span>
<span id="cb50-109"><a href="#cb50-109" aria-hidden="true" tabindex="-1"></a>    <span class="co"># identify the path to the code file</span></span>
<span id="cb50-110"><a href="#cb50-110" aria-hidden="true" tabindex="-1"></a>    path <span class="ot">&lt;-</span> <span class="fu">paste0</span>(path_to_codes, variable, <span class="st">".txt"</span>)</span>
<span id="cb50-111"><a href="#cb50-111" aria-hidden="true" tabindex="-1"></a>    <span class="co"># read in the code file</span></span>
<span id="cb50-112"><a href="#cb50-112" aria-hidden="true" tabindex="-1"></a>    codes <span class="ot">&lt;-</span> <span class="fu">read.table</span>(path, <span class="at">sep =</span> <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>)</span>
<span id="cb50-113"><a href="#cb50-113" aria-hidden="true" tabindex="-1"></a>    <span class="co"># remove the second column (the entries are separated by two \t's)</span></span>
<span id="cb50-114"><a href="#cb50-114" aria-hidden="true" tabindex="-1"></a>    codes <span class="ot">&lt;-</span> codes[, <span class="sc">-</span><span class="dv">2</span>]</span>
<span id="cb50-115"><a href="#cb50-115" aria-hidden="true" tabindex="-1"></a>    <span class="co"># convert the column names</span></span>
<span id="cb50-116"><a href="#cb50-116" aria-hidden="true" tabindex="-1"></a>    <span class="fu">colnames</span>(codes) <span class="ot">&lt;-</span> <span class="fu">c</span>(variable, <span class="fu">paste0</span>(variable, <span class="st">"_name"</span>))</span>
<span id="cb50-117"><a href="#cb50-117" aria-hidden="true" tabindex="-1"></a>    <span class="co"># add the code to the original data frame</span></span>
<span id="cb50-118"><a href="#cb50-118" aria-hidden="true" tabindex="-1"></a>    data <span class="ot">&lt;-</span> <span class="fu">left_join</span>(data, codes, <span class="at">by =</span> variable)</span>
<span id="cb50-119"><a href="#cb50-119" aria-hidden="true" tabindex="-1"></a>    <span class="co"># remove old variable and replace with new variable</span></span>
<span id="cb50-120"><a href="#cb50-120" aria-hidden="true" tabindex="-1"></a>    data[, variable] <span class="ot">&lt;-</span> data[, <span class="fu">paste0</span>(variable, <span class="st">"_name"</span>)]</span>
<span id="cb50-121"><a href="#cb50-121" aria-hidden="true" tabindex="-1"></a>    data <span class="ot">&lt;-</span> data[, <span class="sc">!</span>(<span class="fu">colnames</span>(data) <span class="sc">%in%</span> <span class="fu">paste0</span>(variable, <span class="st">"_name"</span>))]</span>
<span id="cb50-122"><a href="#cb50-122" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb50-123"><a href="#cb50-123" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(data)</span>
<span id="cb50-124"><a href="#cb50-124" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="analysis-eda.rmd" class="level1">
<h1>Analysis: <code>eda.Rmd</code></h1>
<p>Where I go from here depends strongly on what questions I want to ask. If I already know the category of questions I’m planning to ask, and, for example, I know that they fall into two groups, then I will probably make two .Rmd files, one for each question.</p>
<p>If, however, I just want to play around with the data for a while, as is the case here, I will make a .Rmd file called <code>eda.Rmd</code> (or something along those lines).</p>
<p>Sometimes I end up separating my initial exploration file into several separate files when I start to go down several diverging paths.</p>
<p>Regardless of the analysis I decide to conduct, each of my <code>.Rmd</code> files will start with the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"R/load.R"</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"R/clean.R"</span>)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="co"># laod the data</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>time_use_orig <span class="ot">&lt;-</span> <span class="fu">loadData</span>()</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a><span class="co"># clean the data</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>time_use <span class="ot">&lt;-</span> <span class="fu">cleanData</span>(time_use_orig)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The opportunities for analysis are wide open!</p>
</section>
<section id="variables" class="level1">
<h1>List of variables downloaded from ATUX-X</h1>
<ul>
<li>CASEID (ATUS Case ID)</li>
<li>YEAR (Survey year)</li>
<li>NUMCONTACTS_CPS8 (Number of actual and attempted personal contacts)</li>
<li>HRHHID_CPS8 (Household ID (CPS))</li>
<li>HRHHID2_CPS8 (Household ID part 2 (CPS))</li>
<li>STATEFIP (FIPS State Code)</li>
<li>HH_SIZE (Number of people in household)</li>
<li>FAMINCOME (Family income)</li>
<li>HH_NUMKIDS (Number of children under 18 in household)</li>
<li>HH_NUMADULTS (Number of adults in household)</li>
<li>PERNUM (Person number (general))</li>
<li>LINENO (Person line number)</li>
<li>WT06 (Person weight, 2006 methodology)</li>
<li>AGE (Age)</li>
<li>SEX (Sex)</li>
<li>RACE (Race)</li>
<li>HISPAN (Hispanic origin)</li>
<li>ASIAN (Asian origin)</li>
<li>MARST (Marital status)</li>
<li>AGE_CPS8 (Age (CPS))</li>
<li>SEX_CPS8 (Sex (CPS))</li>
<li>EDUC (Highest level of school completed)</li>
<li>EDUCYRS (Years of education)</li>
<li>SCHLCOLL (Enrollment in school or college)</li>
<li>SCHLCOLL_CPS8 (Enrollment in school or college (CPS))</li>
<li>EMPSTAT (Labor force status)</li>
<li>OCC2 (General occupation category, main job)</li>
<li>OCC (Detailed occupation category, main job)</li>
<li>IND2 (General industry classification, main job)</li>
<li>IND (Detailed industry classification, main job)</li>
<li>FULLPART (Full time/part time employment status)</li>
<li>UHRSWORKT (Hours usually worked per week)</li>
<li>UHRSWORK1 (Hours usually worked per week at main job)</li>
<li>UHRSWORK2 (Hours usually worked per week at other jobs)</li>
<li>EARNWEEK (Weekly earnings)</li>
<li>PAIDHOUR (Hourly or non-hourly pay)</li>
<li>EARNRPT (Easiest way to report earnings)</li>
<li>HOURWAGE (Hourly earnings)</li>
<li>HRSATRATE (Hours worked at hourly rate)</li>
<li>OTUSUAL (Usually receives overtime, tips, commission at main job)</li>
<li>OTPAY (Weekly overtime earnings)</li>
<li>UHRSWORKT_CPS8 (Hours usually worked per week (CPS))</li>
<li>UHRSWORK1_CPS8 (Hours usually worked per week at main job (CPS))</li>
<li>UHRSWORK2_CPS8 (Hours usually worked per week at other jobs (CPS))</li>
<li>HRSWORKT_CPS8 (Hours worked last week (CPS))</li>
<li>ACT_CAREHH (ACT: Caring for and helping household members)</li>
<li>ACT_CARENHH (ACT: Caring for and helping non-household members)</li>
<li>ACT_EDUC (ACT: Educational activities)</li>
<li>ACT_FOOD (ACT: Eat and drinking)</li>
<li>ACT_GOVSERV (ACT: Government services and civic obligations)</li>
<li>ACT_HHACT (ACT: Household activities)</li>
<li>ACT_HHSERV (ACT: Household services)</li>
<li>ACT_PCARE (ACT: Personal care)</li>
<li>ACT_PHONE (ACT: Telephone calls)</li>
<li>ACT_PROFSERV (ACT: Professional and personal care services)</li>
<li>ACT_PURCH (ACT: Consumer purchases)</li>
<li>ACT_RELIG (ACT: Religious and spiritual activities)</li>
<li>ACT_SOCIAL (ACT: Socializing, relaxing, and leisure)</li>
<li>ACT_SPORTS (ACT: Sports, exercise, and recreation)</li>
<li>ACT_TRAVEL (ACT: Traveling)</li>
<li>ACT_VOL (ACT: Volunteer activities)</li>
<li>ACT_WORK (ACT: Working and Work-related Activities)</li>
<li>ERS_ASSOC (ERS: Activities associated with primary eating and drinking (travel and waiting))</li>
<li>ERS_PRIM (ERS: Primary eating and drinking)</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/www\.rebeccabarter\.com");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://utteranc.es/client.js" repo="rlbarter/blog_comments" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->




</body></html>